version: '3.9'

services:
  db:
    image: postgres:16.4
    ports:
      - 5432:5432
    restart: always
    shm_size: 1gb
    environment:
      - POSTGRES_PASSWORD=example
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  