name: Publish Family-Libraries to NuGet

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                project:
                    - 'src/Family.Libraries/Family.Libraries.Extensions.Collections/Family.Libraries.Extensions.Collections.csproj'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                    .github
                    src/Family.Libraries
            - name: Setup .NET 8
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x
            - name: Restore dependencies
              run: dotnet build ${{ matrix.project }} --configuration Release
            - name: Pack NuGet package
              run: dotnet pack ${{ matrix.project }} /p:PackageVersion=1.0.${{ github.run_number }} --configuration Release --output ./nupkg
            - name: Publish to Nuget
              run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
              env:
                NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}