name: api
run-name: webui by ${{ github.actor }}
on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
          matrix:
              dotnet-version: [ '8.0.x' ]
      steps:
          - uses: actions/checkout@v4
          - name: Setup dotnet ${{ matrix.dotnet-version }}
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: ${{ matrix.dotnet-version }}
          - name: Display dotnet version
            run: dotnet --version
          - name: Build webui
            run: dotnet build src/webui/WebUI.csproj