name: api
run-name: webui by ${{ github.actor }}
on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
          matrix:
              node-version: [18.x]
      steps:
          - name: Checkout source code
            uses: actions/checkout@v4

          - name: Setup nodejs $
            uses: actions/setup-node@v3
            working-directory: ./src/webui
            with:
              node-version: 18
              cache: npm
              cache-dependency-path: package-lock.json

          - name: Install dependencies
            working-directory: ./src/webui
            run: npm ci
          
          - name: Build webui
            working-directory: ./src/webui
            run: npm run build